# Generated by Django 4.2.7 on 2023-12-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0002_alter_counter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='counter',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='count.ipmodel'),
        ),
    ]
