# Generated by Django 4.2.7 on 2023-12-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0003_ipmodel_counter_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
