# Generated by Django 4.2.7 on 2023-12-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0004_alter_counter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
