# Generated by Django 4.2.7 on 2023-12-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0005_alter_counter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='lat',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='lng',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='counter',
            name='place_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
