# Generated by Django 4.2.7 on 2023-12-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0007_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='duration_min',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
